name: assignment_3
description: "MDEV1005_Assignment_3"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^2.0.4
  flip_card: ^0.5.0
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296
  http: ^0.13.3
  google_fonts: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/tenor.gif
